# Use Node.js image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 5000

RUN apt-get update && apt-get install -y postgresql-client

# Start server
CMD ["npm", "start"]
